### ISSUE TITLE
Epic: Twilio integration for sms alerts 

### ISSUE THREAD

**Issue by manishapriya94** [ProgramEquity/amplify#128]
**User Story:** 
A user can choose to opt into sms alerts around the cause they wrote a letter for. The twilio integration allows us to follow up with user education via SMS. 

<img width="475" alt="Screen Shot 2022-03-16 at 8 15 28 PM" src="https://user-images.githubusercontent.com/9143339/158729581-cafa4565-99f5-4d14-a4b6-5b155952818d.png">

- [ ] Set up Twilio API
  - [ ] Create API token secret 
  - [ ] Route integration 
  - [ ] Build integration tests
- [ ] Feature use: 
  - [ ] User education sequences
  - [ ] Checkbox opt in
- [ ] Update documentation

**Comment by andyfeller** [comment]
Capturing discuss notes working with @nawazkhan and @ankitagrawal98

## Brainstorm on task breakdown

1. Stage 2 needs to be expanded to take advantage of Auth0's SMS passwordless login option (which is through Twilio ironically) detailed https://auth0.com/docs/authenticate/passwordless/authentication-methods/sms-otp in order to allow people to authenticate with their mobile device rather than needing a Google account

   We think the Auth0 passwordless login using the Universal Login flow makes the most sense IF it can provide the phone number used for authenticating

   <img width="792" alt="Screen Shot 2022-04-21 at 1 01 32 PM" src="https://user-images.githubusercontent.com/2089743/164513028-fcad111d-3ed2-4963-b3ba-7cd3fe7e513e.png">

1. Implement necessary database schema changes for containing constituents mobile number, per campaign notification preference as well as UI changes that populate the data

1. Developing a monthly digest process that generates digests around the various campaigns that constituents have signed up for

1. Explore a method for organizers to send out ad-hoc messages to constituents for a given campaign

**Comment by manishapriya94** [comment]
Open source alternative: https://fonoster.com/

cc: @nawazkhan @ankitagrawal98 @andyfeller

**Comment by Iamsoto** [comment]
Hello,

As of now, I'm not seeing a source of the sms message, nor what triggers it.

Do the individual campaign managers have access to Twilio accounts (presumably under some sort of organization) and setup their own flow to call an Amplify API endpoint?
Or are you looking for a more in-house solution where campaign managers can login to Amplify and build and send their own messages and notifications from Amplify?

**Comment by manishapriya94** [comment]
Community user story: The groups often don't have IT people and might create another barrier if they have to have their own tooling. 
- Could the workflow reflect a model in which the group texts some number/mechanism and it will text the end user who has subscribed? 
- Would that include a review process? Or does it need authentication to be able to send to begin the flow? A different Auth0 workflow (currently it validatates constituents, we need new one for the community groups) 
If they go to a branch link  
- Compliance check: 
  - What is the end to end encryption (which plan) 
  - How to architect for identity validation/access management

**Comment by Iamsoto** [comment]
Also. 
HIPAA specifically is for Protected Health Information. I don't see health information stored in Amplify. So I don't believe HIPAA specifically should be a concern for us. Correct me if I'm wrong 

source: 
https://support.twilio.com/hc/en-us/articles/360059959413-Building-HIPAA-Compliant-Messaging-Applications-with-Twilio

**Comment by Iamsoto** [comment]
The California Consumer Privacy Act might be something to be aware of, however: 
And if we're reaching an international audience, The EU has the GDPR. 
Let me know if this seems more relevant. 

Source:
https://oag.ca.gov/privacy/ccpa
https://digitalguardian.com/blog/what-gdpr-general-data-protection-regulation-understanding-and-complying-gdpr-data-protection
