### ISSUE TITLE
Finish ActionComplete page 

### ISSUE THREAD

**Issue by manishapriya94** [ProgramEquity/amplify#215]
<img width="431" alt="Screen Shot 2022-02-22 at 4 25 48 PM" src="https://user-images.githubusercontent.com/66452376/155236841-08d2c72e-aaa7-4cf0-91a1-00b53e3a1db7.png">

**Notes**
- The components are already built (action-complete component in **red** and cause-carousel component in **blue**)
- Assets are provided in [here](https://github.com/ProgramEquity/amplify/tree/94f358237d9a76332dc39023bb7b4bd666fb8101/public/Campaigns)
- Here is a [working draft ](https://github.com/ProgramEquity/amplify/pull/126)with initial stylings and components 

### Tasks

**In action-complete component:**
 
- [x] for expected delivery date, you are using the retrieve method from [Lob API](https://docs.lob.com/#operation/letter_retrieve). Here's our wiki of our use. 
<img width="805" alt="Screen Shot 2022-05-11 at 11 34 09 AM" src="https://user-images.githubusercontent.com/9143339/167936995-f8c9a479-086e-477f-bb72-8dcfd0a4c88c.png">

- [x] We are going to hardcode the representatives in a grid 

**In action-carousel component:**
- [x] Implement the above screenshot in the components on the complete page using [veutify carousel ](https://vuetifyjs.com/en/components/carousels/#usage). You can use two carousels, one for the representatives and one for the bills.
In cause-carousel component
- [x] Figure out how to display the items side by side as seen in the screenshot above instead of hidden behind each other as is default in the carousel. 
- [x] Campaigns are being populated by calling [Campaigns API ](https://github.com/ProgramEquity/amplify/wiki/Campaigns-API-Endpoints)
- [x] Fix this bug of wrapping: https://github.com/ProgramEquity/amplify/issues/150

**Comment by joester030376** [comment]
![image](https://user-images.githubusercontent.com/104450030/169978786-f0158a71-2512-4d72-be6a-1f5242abd133.png)
I pushed the updates of the above issues.
well the problem is there is the proper image of the carousel component.
