### ISSUE TITLE
Security hardening for current actions

### ISSUE THREAD

**Issue by manishapriya94** [ProgramEquity/amplify#23]
- [x] ProgramEquity/amplify-back-end#199
- [ ] ProgramEquity/amplify#20
- [x] ProgramEquity/amplify-back-end#201
- [x] ProgramEquity/amplify-back-end#202

References: 
- [Stack Best Practices](https://docs.google.com/document/d/1rSVpE5v_pdhQlG2b_-2erqDMpDXgNMUWQtgDQB6e-zY/edit?usp=sharing)
- [Security hardening for Actions](https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions)

### Go over to Action Workflows
<img width="690" alt="Screen Shot 2022-02-07 at 9 08 42 PM" src="https://user-images.githubusercontent.com/9143339/153014277-d65505ed-b0f6-49a0-9b26-74a8a2b54a88.png">
