### ISSUE TITLE
Epic: Database Operations (Post ORM Backend Implementation)

### ISSUE THREAD

**Issue by manishapriya94** [ProgramEquity/amplify#31]
## This epic for earth day 4/21 has moved [here ](https://github.com/ProgramEquity/amplify/issues/49)

User Story: 
- User has authenticated 
- Has added their name into the signature box 
- Has added their address into the address box
- User moves to next step (new window triggered) payment added
- Successful payment triggers 'send message' button 
- Send message button creates a letter to send to the representative 
  - **Send message triggers a `POST` to back-end to make a call to LOB API** 
  - **Successful 'send message' should also trigger a `POST` to back-end to save record into the DB** 

**_Development Task_**

**Send User Letter to Lob**
- [x] Create `POST` Function in /api/lob endpoint (lob.js)
- [x] Configure endpoint to accept JSON Objects with Letter information 
- [x] [Lob API `POST` request ](#115 )- [Letters API ](https://docs.lob.com/node#letters_create)
- [x] Send 200 status code upon successful call to Front End
   - Saved in Lob addressbook
- [x] Add Documentation to Wiki Endpoint
- [x] [Sample implementation in documentation](ProgramEquity/amplify#30)

**Save User Letter Data**
- [ ] Create Table in PostgresDB via KNEX migration
- [ ] Seed User Letter Data
- [ ] Create new endpoint `/api/userletter` endpoint
- [ ] Add app.js route information for `/api/userletter`  endpoint
- [ ] Create `GET` function `/api/userletter `
- [ ] Configure to return all user letters that have been created
- [x] ProgramEquity/amplify-back-end#124
- [ ] Configure endpoint to accept JSON Objects with Letter information 
- [ ] Use Knex ORM to[ build insert query](https://knexjs.org/#Builder-insert)
- [ ] Send 200 status code upon successful call to Front End
- [ ] Add Documentation to Wiki Endpoint
- [ ] Sample implementation in documentation

**Comment by manishapriya94** [comment]
Resolved by create_letter function in lob.js
