### ISSUE TITLE
Epic: ORM for database modeling and migrations

### ISSUE THREAD

**Issue by JamesMGreene** [ProgramEquity/amplify#32]
My experiences with Sequelize have all become cautionary tales, so I guided us away from using it at this point and instead favored just using Knex, which is a more basic "SQL query builder".

However, for maintainability's sake, it is probably worthwhile to consider an ORM for the long-term, especially with some contributors not being too familiar with databases.

~~I would suggest we investigate [Prisma](https://www.prisma.io/) as a potential ORM in particular.~~ 🔺

~~I think it has a lot of nice features that make it a more solid choice than Sequelize. It should also be able to completely replace our Knex usage, as far as I can tell at this point.~~

### Tasks

- [x] Install Objection in the codebase: `npm install --save objection`
- [x] Configure Objection in the codebase
  - This requires a one-time configuration something like `require('objection').Model.knex(knexClient)`
- [x] https://github.com/ProgramEquity/amplify/issues/141
- [x] https://github.com/ProgramEquity/amplify/issues/142
- [ ] **BONUS:** https://github.com/ProgramEquity/amplify/issues/143 (:warning: currently unused)
- [ ] **BONUS:** Create a Model for the `constituents` table (:warning: currently unused)
- [ ] **BONUS:** Create a Model for the `sent_letters` table (:warning: currently unused)
- [ ] **BONUS:** Create a Model for the `variants` table (:warning: currently unused)

### Status

- There is a branch created called [`objection-orm`](https://github.com/ProgramEquity/amplify/tree/objection-orm) that installs the `objection` module and sets up the project for creating models.
- Feel free to create branches off that branch and send PRs to it as the base branch
- Models should be created in the `server/db/models/` directory (only exists in the `objection-orm` branch)
- Model filename should be in a singular (not plural) form in all lowercase letters with hyphens as needed, e.g. `letter-version.js`
- Model class name should in a singular (not plural) form in PascalCase letters, e.g. `LetterVersion`

Example, at filename `server/db/models/letter-version.js`:

```js
const Model = require('./_base')

class LetterVersion extends Model {
  static get tableName() {
    return 'letter_versions'
  }

  // ...additional methods, relationships, etc.
}

module.exports = LetterVersion
```

**Comment by waldnzwrld** [comment]
I've been using https://bookshelfjs.org/ in another personal project and I like it. 

It's maintained and widely used. Can I suggest it?

**Comment by manishapriya94** [comment]
Thanks @waldnzwrld! @JamesMGreene, the documentation looks great - do we want to focus on this for wednesday?

**Comment by JamesMGreene** [comment]
> I've been using https://bookshelfjs.org/ in another personal project and I like it.

I've used Bookshelf in the past and been fine with it. 👌🏻 

> It's maintained and widely used.

I would agree that Bookshelf is relatively widely used, though not as widely used as Objection. 👌🏻  

However, on the point of Bookshelf being maintained, I definite disagree. 😕 

Its latest published version on npm is almost 2 years old and its number of open issues are fairly high:

| | Bookshelf | Objection |
|:---|:---:|:---:|
| Last published | 2020-06-07 (~21 months ago) | 2021-12-30 (~3 months ago) |
| Open issues | 222 | 63 (~72% fewer) |
| Weekly downloads | 73,505 | 114,214 (~55% more) |

As far as usage ergonomics go, I found Bookshelf's APIs (e.g. fetching records) to feel a bit unnatural. Using the [`bookshelf-modelbase` plugin](https://github.com/bsiddiqui/bookshelf-modelbase) helps with that, IMHO.

Objection's APIs feel a bit better than Bookshelf's out-of-the-box, IMHO, and _look_ like they are probably more capable of advanced usage in the long haul (`through` relationships, various `JOIN` types, etc.).

Given our project's current needs, I think either one could work fine. 👍🏻 

If I had to pick one, I'd probably start with Objection. 🤷🏻‍♂️
