### ISSUE TITLE
Bug Bashoff: Accessibility bugs & Optimizations

### ISSUE THREAD

**Issue by manishapriya94** [ProgramEquity/amplify#341]
Table of Contents 

## User Story
<img width="335" alt="Screen Shot 2022-10-12 at 11 52 50 AM" src="https://user-images.githubusercontent.com/9143339/195425140-6efbd598-1774-4352-a250-a4dc227c8f5e.png">

## Goal State and Wotkflow: 
![image](https://user-images.githubusercontent.com/9143339/195422072-c26d7113-7efe-4b2a-ae1d-06c0123b50a7.png)
- [Walkthrough app](https://amplify-app-production.herokuapp.com/)
- Log any bugs using Bug template (Potential optimization [here](https://docs.google.com/document/d/1a3NIE2QOD4BvBgr5SVumB_bdU1tEt8VKKBkynlXVU3A/edit?usp=sharing))
- Solve ones in progress or Ideate 

**Optimizations to Ideate**
- [Multilingual ](https://www.google.com/aclk?sa=l&ai=DChcSEwim18KogNv6AhXQEa0GHduMD7UYABAAGgJwdg&sig=AOD64_1Z5isdvZ3kgiioPxUSydERM_Xz3Q&q&adurl&ved=2ahUKEwi3rruogNv6AhWIK0QIHT-tC18Q0Qx6BAgCEAE)
- [Speech to text ](https://codepen.io/aburai/pen/bzwLdz)

**Resources** 
- [Amplify Components](https://github.com/ProgramEquity/amplify/tree/main/src/components)
- [Bug Template](https://github.com/ProgramEquity/amplify/issues/new?assignees=teakopp&labels=QA&template=bug.md&title=QA+Bug)
- [A11y Trainin](https://github.rewatch.com/video/0jel75z7fxsdu5lo-intro-to-web-accessibility-a11y-sept-dol)

## Bugs we've found that you can solve
- [x] [Accessibility focus on mobile](https://github.com/ProgramEquity/amplify/issues/334)
- [x] [Bug: Text Wrapping](https://github.com/ProgramEquity/amplify/issues/298)
- [x] 🖼️ Extract CSS in the representative card and use classes instead of inline styling. [#331](https://github.com/ProgramEquity/amplify/issues/331)
- [x] 🖼️⚙️ Enable cropping of the representative photos using the data provided by the Cicero API. [#333](https://github.com/ProgramEquity/amplify/issues/333)
  - [x] ⚙️ Examine the photo_cropping property.
  - [x] ⚙️ Plan out any modifications that need to be carried out before sending it to the front-end.
  - [x] 🖼️ Apply inline styling to the photos being displayed in individual representative cards to crop them.
- [x] 🖼️⚙️ Display popular social media icons for representatives. [#295](https://github.com/ProgramEquity/amplify/issues/295)
- [x] 🖼️ Fix the display of form in the campaign page — The filters are often overlapped by the submit button. [#332](https://github.com/ProgramEquity/amplify/issues/332)

**Comment by eprice555** [comment]
@manishapriya94 hi this is a test on any changes

**Comment by paramsiddharth** [comment]
> 

@eprice555 It works perfectly!
![image](https://user-images.githubusercontent.com/30315706/195434329-a2eab45c-6ee7-496d-a650-5cd1a3b29c68.png)
