### ISSUE TITLE
Implement logging

### ISSUE THREAD

**Issue by DietBepis1** [ProgramEquity/amplify#406]
We are at the point where it is becoming imperative to be able to monitor Amplify's production deployments. During the Sogorea Te' onboarding event, we received dozens of donations, but many of them ultimately failed to process and refunds were issued. Those refunds are potentially hundreds or thousands of donation dollars that may be lost forever. If we had logging, those issues may have been able to be resolved in the moment.

Proposal: Implement logging using [Winston](https://github.com/winstonjs/winston). It is a non-blocking logging library that can log to anything from a plain text file to SASS services like [Datadog](https://www.datadoghq.com/).

To Do:
- [ ]  Set up base Winston.
- [ ] Implement and document logging levels + Amplify best practices.
- [ ] Research logging services and what logging ability that Heroku can give.
- [ ] Integrate with chosen provider.

**Comment by rsensenig** [comment]
I'm currently working on reading up on the Winston documentation. My next step will be then to implement Winston on a simple Vue app that I created to test out how it works, and then work on setting up base Winston for Amplify.
