### ISSUE TITLE
Subtask Send Letter: Checkout button

### ISSUE THREAD

**Issue by manishapriya94** [ProgramEquity/amplify#44]
**What screen is this?**
## Screen 7: Send Letter
<img width="473" alt="Screen Shot 2022-01-20 at 8 57 08 PM" src="https://user-images.githubusercontent.com/9143339/150470433-9a9111b7-7a21-4d13-963a-e38747558787.png">

## Which component? Which piece of copy or graphic?
The text on the final action button at the bottom 
<img width="391" alt="Screen Shot 2022-01-20 at 9 23 55 PM" src="https://user-images.githubusercontent.com/9143339/150470831-11dec387-584e-4325-8db9-78483cfb1ef4.png">

**What is the change propoosed? (add a figma screenshot, follow the workflow here)**
Change words to simplify language but still convey you are doing 2 actions (payment via stripe and sending post)

**Which topic does this educate the constituent around? (add a short description on how its clearer than the original) ?**

_Advocacy values to consider:_
- [ ] Testimonials should be personal
- [x] Language should be simple
- [ ] People are lead by causes and their impact
- [ ] Accessibility across abilities 

**What are frontend tasks?** (if theres any tasks needed outside of the template below, pick a different color like blue) 
 - [ ] Add image here in this file 
 - [x] Insert copy in this file 

_List files that need to be changed next to task_

**CC:** @frontend-team member, @frontend-coordinator, @research-coordinator 

--------------------------
For Coordinator
- [ ] add appropriate labels: "good-first-issue", "design", "screen label", "intermediate"
- [ ] assign time label 
- [ ] Approved and on project board
