### ISSUE TITLE
Review Letter: Panel Transitioning Commands

### ISSUE THREAD

**Issue by mahrsbar** [ProgramEquity/amplify#45]
### Panel Transitioning commands
To ease the transitions across the 3 steps before sending letter, we want to use the 'enter command' to signify moving to the next step and implement locking for the accordion steps. 
<img width="269" alt="Screen Shot 2022-02-10 at 9 36 54 AM" src="https://user-images.githubusercontent.com/66452376/153453565-7947ba8b-6f64-4fb8-a069-cac3da38d034.png">

### Tasks
- [x] Create "next" buttons for each accordion panel 
- [ ] Create default, in progress and complete styles for the accordion as seen in the screenshot below:
<img width="343" alt="Screen Shot 2022-02-10 at 9 40 59 AM" src="https://user-images.githubusercontent.com/66452376/153454271-b146d7d2-a2f0-4e02-9f3e-1e0d2cc161af.png">

- [ ] Implement functionality so user is required to complete the steps in order

**Comment by manishapriya94** [comment]
@nawazkhan @nawazeverlane
