### ISSUE TITLE
Getting started with Actions 

### ISSUE THREAD

**Issue by manishapriya94** [ProgramEquity/amplify#457]
### Description
Open source maintainers try the best they can, actions are automations that can add workflows that bring us together in our collaboration. Thats the theme as we ramp with the tasks below.  

### Spec
User story: what kind of Action would make people more welcome to this project with either
- helpful prompts or reminders 
- help us communicate better 
- coordinate some of the project's details

### Resources: 
- [What is an Action ](https://docs.github.com/en/actions)
- How to use Copilot to write your action [recording](https://www.notion.so/programequity/GitHub-workflows-with-Codespaces-Copilot-655b6cdca0344daf9e2bcd351e53b24d)
- If you're done with your task and want to suggest one of your own, check out [marketplace ](https://github.com/marketplace?type=actions)

### Tasks: 
**Collaboration** : Including communication and engagement tools 
- [ ] 🎢  welcome messages 
- [ ] 🛒 [Awake Yet Action](#447 ) 
- [ ] 🎢  [labeler](https://github.com/actions/labeler)
- [x] 🛒 [Spellcheck](https://github.com/austenstone/spellchecker-cli-action-summary) by @austenstone! 

------------------------
### Target Date: 
2022-02-22 
Maintainers for reference are attached in assignments
Pair Hour Mentors: assign yourself in each task when its ready to review
