### ISSUE TITLE
 Epic Outline: Letter Payment

### ISSUE THREAD

**Issue by manishapriya94** [ProgramEquity/amplify#46]
## Context: 
This is part of the features of the Letter Payment Epic ProgramEquity/amplify-front-end#45. The user is informed about the minimum cost of a letter and then offered donation options that can be checked out. 
<img width="420" alt="Screen Shot 2022-02-10 at 9 07 33 AM" src="https://user-images.githubusercontent.com/66452376/153447673-0d0aade6-43d1-45f4-952d-e84d7a1eefd6.png">

## To do: 
- [ ] Create a donation progress bar (user story [here](ProgramEquity/product#31)). This values are currently not available to us, so you can use placeholder values. Look into this [progress bar vuetify](https://vuetifyjs.com/en/components/progress-linear/#usage) component for help.
- [ ] Create a checkbox that allows for user to receive a gift as seen above. This will not be stored anywhere at the moment.
- [ ] Implement letter payment following these [steps](https://github.com/ProgramEquity/amplify-back-end/wiki/Stripe-API-Enpoint). 
The user story is as followed:
- User picks a donation amount
- User can choose to send letter without donation amount (value send to api would be '1'
- User is directed to complete transaction via stripe checkout
- Once payment is successful, letter is sent
