### ISSUE TITLE
Update front-end to prepare for Stripe update

### ISSUE THREAD

**Issue by DietBepis1** [ProgramEquity/amplify#521]
Amplify has a `Constituents` table to store user data; however, it is currently unused. You can see in the wiki that the `Constituents` table should have a `first_name` and `last_name` field. To prepare the app to store constituent data, the front-end will need to be modified in a number of ways.

**Todos:**
- [ ] Update the `SignName` component to have a first name and last name field. There is already a data validation for name that can be copied over.
- [ ] Update the Vuex store to have a first name and last name property for the `userData` object.
- [ ] There is actually a bug in the `TakeAction.nextPage`method that is overriding userData with an empty object. Fix this method so it doesn't write over the data that the user just filled out.
- [ ] I believe that Lob only has a `name` property for the letter, so create a computed property that concatenates the user's name together for both the letter display and also when the user is passed to `/createLetter`.
- [ ]  Any other spots that need fixing that I might have missed.

**Comment by lokeshkumar0001** [comment]
Hi @DietBepis1, I am a full stack developer but new to open source. Pls guide me on how can I get started with contributing to this organization

**Comment by paramsiddharth** [comment]
@lokeshkumar0001 Hey Lokesh, welcome to open-source and Program Equity! 😊 I would recommend you have a look at the codebase and the issue details and ask any specific questions you come across.

**Comment by lokeshkumar0001** [comment]
@paramsiddharth Thanks for your help. May I know where to ask any specific questions. Do you have any slack or discord channels? or anything like that?

**Comment by paramsiddharth** [comment]
> @paramsiddharth Thanks for your help. May I know where to ask any specific questions. Do you have any slack or discord channels? or anything like that?

@lokeshkumar0001 Sure! Here's our Slack: https://join.slack.com/t/programequity/shared_invite/zt-1p1buco3b-yUXjDaKSz3OSJfaHj88Y4g

**Comment by smgraywood** [comment]
Hi all! I'm going to pick this up, if that's ok with everyone! Glenn sent it to my pod leader as something that I might be able to contribute on.

**Comment by christina-ml** [comment]
I worked on the first todo item for the `SignName` component:
Update the SignName component to have a first name and last name field. There is already a data validation for name that can be copied over.

Notes:
- Remove `name` text field
- Add `firstName` text field
  - Update rule to require `firstName` field
  - Update placeholder text
- Add `lastName` text field
  - Update rule to require `lastName` field
  - Update placeholder text
- Update data object with `firstName` and `lastName` fields
- Update computed form() function with `first_name` and `last_name` fields

Pull request: https://github.com/ProgramEquity/amplify/pull/547

**Comment by Dunridge** [comment]
Branch: [issue-521](https://github.com/ProgramEquity/amplify/tree/issue-521)

**Comment by santi-jose** [comment]
hi @Dunridge and @christina-ml are you working on this issue? I would like to collaborate if so. If you aren't, I can take care of it! Thanks

**Comment by christina-ml** [comment]
@santi-jose @Dunridge  I have updated my Pull Request #547. Can someone please review my pull request, to see if it can be merged?

**Comment by christina-ml** [comment]
Feel free to assign yourself to work on this issue 🙂

**Comment by davidchapuis** [comment]
Hi @christina-ml nice to see you here
@santi-jose this issue is outdated I will close it
You can have a look at https://github.com/OpenSourceFellows/amplify_docs/discussions/11 for front-end issues, hope that helps
