### ISSUE TITLE
Template for larger Epic Issue

### ISSUE THREAD

**Issue by Alex-is-Gonzalez** [ProgramEquity/amplify#613]
### Target Date: yyyy-mm-dd

**Please consider (or make a note) of anyone who is on-call or on support during this feature! This should be included in the timeline**

### Done Done 

- [ ] Is unit tested
- [ ] Is covered by integration tests
- [ ] UX Automation Added
- [ ] Is continuously tested in each environment
- [ ] Monitoring and Diagnostics added
- [ ] Is sufficient user telemetry and Dashboarding
- [ ] Relevant architectural review
- [ ] Is sufficient public documentation
- [ ] CSS and team has been appropriately briefed on how to support
- [ ] Engineering Lead signoff
- [ ] PM signed off
- [ ] Design signed off
- [ ] Customer value demo screencast sent to team

**Comment by Dunridge** [comment]
Branch: [issue-613](https://github.com/ProgramEquity/amplify/tree/issue-613)

**Comment by Dunridge** [comment]
Branch: [issue-613](https://github.com/ProgramEquity/amplify/tree/issue-613)

**Comment by Dunridge** [comment]
Branch: [issue-613](https://github.com/ProgramEquity/amplify/tree/issue-613)
