### ISSUE TITLE
Sunrise Launch Checklist

### ISSUE THREAD

**Issue by manishapriya94** [ProgramEquity/amplify#79]
Thank you folks for coordinating hackathon ships into a recombined repo! Sunrise would like to do a test run on February 26th - is this feasible? 

Heres whats remaining (yellow in [product map](https://docs.google.com/spreadsheets/d/1uEhgbXIrLHz-IrAuiBTRzEMJ_QfahJJlN7J1OmqT-so/edit?usp=sharing)): 

Outreach @manishapriya94 : 
- [ ] add lob letter templates 
- [ ] add each campaign to database 
- [ ] add column in campaigns for logo pictures

Frontend @mahrsbar: 
- [ ] add coupon code ability to payment 
- [ ] finish checkout flow 
- [ ] finish action complete page 

Backend @nawazkhan @teakopp: 
- [ ] update stripe wiki 
- [ ] connect applepay to stripe checkout 

Architecture @JamesMGreene : 
- [ ] create production environment for just sunrise
- [ ] connect it to google domain
